language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  # - "3.7"
  - "3.5-dev" # 3.5 development branch
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev
# command to install dependencies
install: "pip install -r requirements.txt"
matrix:
  allow_failures:
    - python: 3.5-dev
    - python: 3.6-dev
    # - python: 3.7
    - python: 3.7-dev
    - python: nightly
branches:
 only:
  - master
  - dev
# command to run tests
script: python tests.py
